mpc:
  Ts: 0.03          # longer control step (fewer QP solves)
  N: 5             # shorter horizon
  Q: [20.0, 1.0, 300.0, 30.0]
  R: 0.5
  dR: 0.5
  u_min: -10.0
  u_max: 10.0
  terminal_weight: 0.0
  use_lqr_terminal: true
  solver: "OSQP"
