# Outer: cart PD -> theta_ref (radians)
cart_pid:
  Kp: 0.02
  Ki: 0.0
  Kd: 0.08
theta_ref_limit: 0.12   # optional; set to null to remove clamp

# Inner: pendulum angle PD
pend_pid:
  Kp: 12.0
  Ki: 0.0
  Kd: 4.0
