pid_pid:
  # Angle PID (use your found gains)
  angle_pid:
    Kp: -283.449
    Ki: 0.0
    Kd: -11.027

  # Cart PID (use your found gains)
  cart_pid:
    Kp: 0.693
    Ki: 0.0
    Kd: -1.228

  # References
  theta_ref: 0.0   # rad
  x_ref: 0.1       # m default if ref lacks x_ref

  # Implementation details
  u_limit: 80.0        # [N]  --- SATURATION limit
  integ_limit: 5.0     # [arb] --- ANTI-WINDUP clamp for both integrators